baseURL = "https://hugoscss.netlify.com/"
languageCode = "en-us"
title = "Hugo Bootstrap 4 | SCSS Edition"

theme = ["t1"]

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = 1

[params]
# Set SASS variable via site config ...
moo = "green"


